- name: install maven # java
  ansible.builtin.package:
    name: maven
    state: present

- name: create a roboshop user
  ansible.builtin.user:
    name: roboshop

- name: remove the app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: create a app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download shipping application
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
    dest: /tmp

- name: Extract shipping application in shipping server app directory
  ansible.builtin.unarchive:
    src: /tmp/shipping.zip
    dest: /app
    remote_src: yes

- name: Install dependencies # Change the directory to app
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: move the file
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app

- name: create shipping service # we have already had a shipping.service file in repostiry , hence copying to actual path.
  ansible.builtin.copy:
    src: shipping.service
    dest: /etc/systemd/system/shipping.service

- name: Just force systemd to reread configs
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: install mysql client
  ansible.builtin.dnf:
    name: mysql
    state: present

# - name: load the data
#   ansible.builtin.shell: mysql -h mysql.dhanaskanda.online -uroot -p{{mysql_password}} < /app/schema/shipping.sql

- name: check cities schema exists or not
  ansible.builtin.command:  mysql -h mysql.dhanaskanda.online -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
  register: schema

- name: print output
  ansible.builtin.debug:
    msg: "schema output: {{schema}}"

- name: load cities data
  ansible.builtin.shell: "mysql -h mysql.dhanaskanda.online -uroot -p{{mysql_password}}  < /app/schema/shipping.sql"
  when: schema.stdout != "1"

- name: start and enable shipping
  ansible.builtin.service:
    name: shipping
    state: restarted
    enabled: yes