- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: nodejs setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: mongo data
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb-setup

- name: system service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd