- name: Disable mysql8 version
  ansible.builtin.command: dnf module disable mysql -y

- name: Setup the MySQL5.7 repo file 
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MySQL server
  ansible.builtin.dnf:
    name: mysql-community-server
    state: present

- name: start and enable the mysql service
  ansible.builtin.service:
    name: mysqld
    state: restarted
    enabled: true

- name: set root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1