- name: setup MongoDB repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb-client
  ansible.builtin.package:
    name: mongodb-org-shell
    state: present

- name: "Get the {{component}} entries count"
  ansible.builtin.shell: mongo --host mongodb.dhanaskanda.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: entries_count
  when: component == "catalogue"

- name: "Get the {{component}} entries count"
  ansible.builtin.shell: mongo --host mongodb.dhanaskanda.online --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
  register: entries_count
  when: component == "user"

# - name: print the count
#   ansible.builtin.debug:
#     msg: "Product count: {{product_count}}"

- name: "Load the {{component}} data"
  ansible.builtin.shell: "mongo --host mongodb.dhanaskanda.online < /app/schema/{{component}}.js"
  when: entries_count.stdout == "0"